### ISSUE TITLE
Infection unknown will show as non-infection

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb#17]
example: https://covdb.stanford.edu/search-drdb/?article=Wilhelm21b&host=human&variant=Omicron
20 samples from Wilhelm21b are people with infection and two doses of BNT. The variant and date of infection are uncertain, so the database doesn't contain the infected iso name. The data is grouped with people without infection and two doses of BNT.

**Comment by KaimingTao** [comment]
I've added both a pseudo variant and a isolate called "unknown"

**Comment by philiptzou** [comment]
@KaimingTao Do you mean that unknown infection should be treated as no infection? However according to your description, the "unknown" actually means the person was infected without further information. They are still "previously infected".

**Comment by KaimingTao** [comment]
> @KaimingTao Do you mean that unknown infection should be treated as no infection? However according to your description, the "unknown" actually means the person was infected without further information. They are still "previously infected".

I've already solved it on Dec 9, by adding "Unknown variant" as the infection name. Sorry for not closing the issue.
