### ISSUE TITLE
Schema didn't match with autofill command

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb#33]
Related table: subjects and subject_infections
Related columns: immune_status, severity
Related repo and commit: covid-drdb-payload, https://github.com/hivdb/covid-drdb-payload/tree/d604d8e246bee3b2d7bcc01171198abcb300b4f7 (newest version)

**Comment by KaimingTao** [comment]
<img width="1047" alt="Screen Shot 2022-04-12 at 12 57 25 PM" src="https://user-images.githubusercontent.com/988193/163043841-84718671-b229-4452-9bdb-02627d19d3bd.png">

**Comment by philiptzou** [comment]
@KaimingTao It looks like you should update your payload/ repo.
