### ISSUE TITLE
Keeton R - data are inaccurate

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb#7]
**Describe the error**
The data dont match what is in the text and in the figure. First the number 58 is too high and I cant find the titers anywhere. Additionally, we need to add the fact that some of the patients were previously infected with a B.1 like virus (first wave) and others were infected with B.1.351 (second wave). Thats why there is no difference between D614G and B.1.351. Without adding this field the data seem to contradict all of the other studies.

**Comment by philiptzou** [comment]
This issue is resolved by 0d162133b610c46f1559185fe61419ce2f3109bc and frontend change hivdb/chiro-frontend@f76efd02b275f1cb0b493bac68ebce299a26d0ed.

**Comment by philiptzou** [comment]
<img width="1342" alt="Screen Shot 2021-09-14 at 2 19 53 PM" src="https://user-images.githubusercontent.com/809865/133335497-b6ec2c1a-7255-4b3b-9d2f-7ae3e708366a.png">
